### PR TITLE
is_baby column cleaning

### PR DESCRIPTION
**Pull request by SideLair**
A few cosmetic changes related to a misnamed column in an early stage of notebook. Also added some semicolons.

### CODE REVIEW

**Comment by frenzymadness** [comment]
The `rename` command is there just to show it how it works and that it's possible to rename a column. It's up to us whether we rename it from `is baby` to `is_baby` or vice versa. Is this way the one you prefer?

**Comment by SideLair** [comment]
It's ok in guided lesson when lecturer informs about purpose. 
In case of self-study it seems better to me to keep wrong named field in data and then renamed it under control.

But I didn't see your point of view and now this PR seems kind a unimportant to me. So feel free to ignore it :)

**Comment by frenzymadness** [comment]
It depends on what is the wrong name for you. I'd say that using spaces in the column names is not ideal so we can keep "is baby" in data and show how to rename the column together with the benefit of using `data.is_baby` after that on the workshop. What do you think?

**Comment by SideLair** [comment]
Sounds good, but please notice there are other fields with space in this dataset. That's the reason why I'm considering 'is baby' as default. Just to keep notation consistent in whole header.

So let's make it inverse to my PR. Let's keep 'is baby' prepared for renaming and change rest of space-using fields to snake_case. What do you think?

**Comment by frenzymadness** [comment]
Sounds good to me.

**Comment by frenzymadness** [comment]
I've decided to keep spaces in the columns' names and only rename "is baby" to "is_baby" to show the dot notation.

**Pull request closed without merging**
